use jobsmith::templates;

mod common;

#[tokio::test]
async fn cv_typst_source_contains_each_section_exactly_once() {
    let profile = common::dummy_profile();
    let vacancy = common::dummy_vacancy_detail();
    // Summary-only AI draft, per the build_cv_draft_prompt contract:
    // profile sections come from the template, not from the model.
    let cv_content = "Опытный Rust-инженер с фокусом на надёжные backend-сервисы.";

    let output_dir =
        std::env::temp_dir().join(format!("jobsmith-templates-test-{}", std::process::id()));
    tokio::fs::create_dir_all(&output_dir).await.unwrap();

    let typ_path = templates::generate_cv_typst(&profile, &vacancy, cv_content, &output_dir)
        .await
        .unwrap();
    let source = tokio::fs::read_to_string(&typ_path).await.unwrap();
    // best-effort cleanup of the temp dir; assertion below is what matters
    let _ = tokio::fs::remove_dir_all(&output_dir).await;

    for section in [
        "== Профессиональное резюме",
        "== Опыт работы",
        "== Навыки",
        "== Образование",
        "== Сертификаты и курсы",
        "== Языки",
        "== Публикации и проекты",
    ] {
        assert_eq!(
            source.matches(section).count(),
            1,
            "section {section:?} must appear exactly once in the generated .typ"
        );
    }
}

/// End-to-end: a CV generated by the real pipeline (with escaping)
/// must compile with the actual `typst` binary. Skipped when typst is
/// not installed (e.g. on CI runners without it).
#[tokio::test]
async fn generated_cv_compiles_with_real_typst() {
    if std::process::Command::new("typst")
        .arg("--version")
        .output()
        .is_err()
    {
        eprintln!("skipping: typst binary not installed");
        return;
    }

    let profile = common::dummy_profile();
    let vacancy = common::dummy_vacancy_detail();
    // Hostile-ish AI content: markdown heading plus a Typst directive,
    // routed through the real escaping.
    let cv_content = "Инженер с фокусом на надёжность.\n## Опыт\nСм. #read(\"x\") — литерал.";

    let output_dir =
        std::env::temp_dir().join(format!("jobsmith-typst-e2e-{}", std::process::id()));
    tokio::fs::create_dir_all(&output_dir).await.unwrap();

    let typ_path = templates::generate_cv_typst(&profile, &vacancy, cv_content, &output_dir)
        .await
        .unwrap();
    let pdf_path = output_dir.join("cv_e2e.pdf");
    let result = templates::compile_typst(&typ_path, &pdf_path).await;
    let pdf_len = std::fs::metadata(&pdf_path).map(|m| m.len()).unwrap_or(0);
    // best-effort cleanup of the temp dir
    let _ = tokio::fs::remove_dir_all(&output_dir).await;

    result.expect("typst compilation of a generated CV must succeed");
    assert!(pdf_len > 1000, "PDF suspiciously small: {pdf_len} bytes");
}
